### ISSUE TITLE
Consider multihash support/standard?

### ISSUE THREAD

**Issue by rmlearney-digicatapult** [WebOfTrust/cesride#150]
The multiformats work that has emerged from Protocol Labs (https://multiformats.io) is making good progress developing self-describing hashing https://multiformats.io/multihash/, with tooling and support available in multiple languages here: https://github.com/multiformats/multihash

Is there value in bringing this work into CESR?

**Comment by SmithSamuelM** [comment]
CESR supports similar types of formats as the Multiformats work. CESR goes beyond what one can do in multiformats in several very important ways. 

1) CESR native format is text. This makes it easier to develop with, to reason about, to debug all the reasons for a text based encoding. Multihash is a binary encoding, however any binary encoding has as a subset some codes that are equivalent to text codes. Using those subsets, albeit clever, makes the protocol messy.

2) CESR supports round trip text to binary binary to text composability across concatenation for en masse conversion to/from each format. So with CESR you get the performance and bandwidth savings of binary when transmitting over the wire without having to build, debug, and develop in binary. CESR avoids the binary vs text encoding wars because its both at the same time.

3) CESR supports pipelining so its future proofed at scale.

4) CESR uses a set of code tables whose usage and size are prioritized based on demand. The most compact tables are reserved for the codes that are used the most. The least used codes are relagated to less compact tables. The total code space for CESR is in the hundreds of thousands of codes but the most compact codes are 1 char. This further optimizes the over the wire footprint of CESR. The philosophy of CESR is that we add to the code tables on an as needed basis. So we don't pre-populate code tables. So things stay simpler longer. The flexibility of the CESR encodings (fixed length and variable length) enables better optimization of the over the wire without sacrificing the ease of use of a text native orientation. This flexibiity also means that if anyone has a need for an encoding that has already been worked out for multi-formats is should be easy to map it to a CESR equivalent that thereby imbues it with text-to-binary composability.

5) CESR includes all cryptographic primitives not merely hashes, this includes salts, private keys, public keys, signatures, encrypted data.  In this respect multihash and multiformats are way behind.  

6) CESR supports count codes that allow hierarchical composition of primitives into packed structure like primitives. Thus CESR enables CBOR like expressiveness in a text-binary composable encoding. Thus CESR is composable along two different composition axes. Text-to-binary-to-text composition of concatenated primitives. And hierarchical composition into nested structures which are themselves composable text-to-binary-to-text.

**Comment by rmlearney-digicatapult** [comment]
Thanks for the insights 👍

Perhaps worth sharing back in the other direction.
